---
- name: Create Azure PostgreSQL Flexible Server
  hosts: localhost  # We are running the commands through the Azure CLI
  connection: local  # We are running the cmmands on the Ansible control server provided by the Azure CLI
  gather_facts: false

  vars:
    resource_group: mypostgres123
    location: westus2
    server_name: david-postgresserver-1462
    admin_user: username # Replace with username
    admin_password: Password  # Replace with a strong password
    sku_name: Standard_B1ms

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: present
      register: rg

    - name: Create PostgreSQL Flexible Server
      azure.azcollection.azure_rm_postgresqlflexibleserver:
        name: "{{ server_name }}"
        resource_group: "{{ resource_group }}"
         # name: "{{ resource_group }}"
          # name: "{{ .id }}"resource_group }}"
          # location: "{{ location }}"
        # location: "{{ location }}"
        sku: 
          name: Standard_B1ms
          tier: Burstable
        storage:
          storage_size_gb: 128
        administrator_login: "{{ admin_user }}"
        administrator_login_password: "{{ admin_password }}"
        state: present
        version: 17
      register: postgres_server

    - name: Display server details
      debug:
        msg: "PostgreSQL server created: {{ postgres_server }}"
